"""create lon-lat index for building

Revision ID: 89822feb7b86
Revises: a8db60aa1dcd
Create Date: 2025-10-27 10:16:46.265914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89822feb7b86'
down_revision: Union[str, Sequence[str], None] = 'a8db60aa1dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_buildings_lon_lat', 'buildings', ['longitude', 'latitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_buildings_lon_lat', table_name='buildings')
    # ### end Alembic commands ###
