services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ../.
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ..:/app
    ports:
      - "8000:8000"


volumes:
  pg_data:
